# -*- coding: utf-8 -*-
"""Tarea1_SLL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KQyEw3z1cnC6rYeynpAayC10jJFzp9a

### **Sheila Leyva López.**

# Tarea

1. Ejercicio introductorio
"""

doll = 75
clown = 112
c = input("Introduzca el número de payasos vendidos: ")
d = input("Introduzca el número de muñecas vendidas: ")

totalc = clown*int(c)
  
totald = doll*int(d)
 
total = totalc + totald
print ("El peso de su envío es: ",int (total),"g"  )

"""2. Ejercicio de cadena"""

email = input("Ingrese su correo electrónico: ")

arro = email.find('@')

nemail = email[:arro]

print ("Tu email institucional es: ", nemail + "@uaq.com.mx")

"""3. Ejercicio de condicionales"""

print("Renta Anual")
print("1. Menos de $10000")
print("2. Entre $10000 y $20000")
print("3.Entre $20000 y $35000")
print("4. Entre $35000 y $60000")
print("5. Más de 60000")
renta = input("Introduzca su opción de renta anual: ")


if renta == 1:
  print("Su impositivo es del 5%")

elif renta == 2:
  print("Su impositivo es del 15%")

elif renta == 3:
  print("Su impositivo es del 20%")

elif renta == 4:
  print("Su impositivo es del 30%")

else:
  print("Su impositivo es del 45%")

"""4. Ejercicio de bucles"""

pw = input("Introduzca su contraseña: ")
print("Contraseña almacenada")
flag = True

while(flag):  
  pwc = input("Confirmar contraseña: ")
  if pw == pwc:
    print("Las contraseñas coinciden")
    flag = False
  else:
    print("Las contraseñas no coinciden. Intente nuevamente ")

"""5. Ejercicio de lista"""

abc = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

del abc[::3]

print(abc)

"""6. Ejercicio de diccionario"""

#art1 = input("Por favor introduzca el nombre del artículo seleccionado: ")
#precio1 = input("Por favor introduzca el precio del artículo seleccionado: ")
from tabulate import tabulate
flag = True
total = 0
lista = []
diccionario = {}

while (flag):

  d = input("¿Desea agregar un artículo? 1-Sí, 2-No :")

  if (d == '1'):
   
    art = input("Por favor introduzca el nombre del artículo seleccionado: ")
    precio = input("Por favor introduzca el precio del artículo seleccionado: ")
    
    diccionario[art] = precio
    print("Artículo agregado")
  
  else:
    flag = False 
    
    items = diccionario.items()
    
    for art, precio in items:
      total = total + int(precio)

    for art, precio in items:
      print ("Artículo:", art, "$", precio)
    print ("Total: $", total)

"""7. Ejercicio de funciones"""

import numpy as np
num = []
dic = {}
flag = 1

while(flag):
  s = input("¿Desea agregar un número? a)-Sí, b)-No: ")


  if s == 'a':
    num.append(float(input("Introduzca número: ")))
    
   
  else:
    flag = 0
    num = np.array(num)
    dic['media'] = num.mean()
    dic['varianza'] = num.var()
    dic['desviacion'] = num.std()
    print("La media, varianza y desviación de su lista de números se muestran a continuación:")
    print(dic)

"""# Ejercicios en clase

División de enteros
"""

n = input("Introduce el primer número:" )
n = int(n)
m = input("Introduce el segundo número:" )
m = int(m)
c = str(n//m)
r = str(n%m)
print( n, "entre", m, "es igual a", c, "y tiene como residuo", r)

"""Cálculo de IMC"""

peso = input("Introduce tu peso en kg:" )
peso = float(peso)
estatura = input("Introduce tu estatura en m:" )
estatura = float(estatura)
imc = (peso/estatura**2)

print ("Tu índice de masa corporal es: ", round(imc,2))

"""len() y upper()"""

name = input("Ingrese su nombre: ")
ln = len(name)
print("Su nombre", name.upper(),"tiene",ln,"letras")

"""replace()"""

word = input("Ingrese la frase que desee: ")
vocal = input("Introduzca la vocal en minúscula que desee cambiar por mayúsculas dentro de su frase: ")
print (word.replace(vocal, vocal.upper()))

"""Diccionario frutas"""

fruits = {"plátano": 1.35, "manzana": 0.8, "pera": 0.85, "naranja": 0.70}
fruit = input("¿Qué fruta desea?: ")
cant = input("¿Cuántos kilogramos requiere?: ")
cant = float(cant)
if fruit in fruits:
  print(cant, "kilogramos de", fruit,"cuestan",round(fruits[fruit]*cant,2))
else:
  print("La fruta", fruit,"que usted desea no está disponible")

"""Puntuación del empleado"""

flag = True
dinero = float(2400)
while (flag):
  puntuacion = float(input("Por favor introduzca la puntuación del empleado: "))

  if puntuacion == 0.0:
    print("Nivel: Inaceptable. Dinero a recibir: ", dinero*puntuacion, "euros")
    flag = False
  elif puntuacion == 0.4:
    print("Nivel: Aaceptable. Dinero a recibir: ", dinero*puntuacion, "euros")
    flag = False
  elif puntuacion >= 0.6:
    print("Nivel: Meritorio. Dinero a recibir: ", dinero*puntuacion, "euros")
    flag = False
  else: 
    print("Error al introducir la puntuación. Por repita el paso ")

"""**MCD** y mcm"""

def MCD(n,m):
  rest = 0
  while(m>0):
    rest = m
    m = n % m
    n = rest 
  return n

def mcm(n,m):
  mcm = (n*m)/MCD(n,m)
  return (mcm)

n = int(input("Ingresa un primer número: "))
m = int(input("Ingresa un segundo número: "))

print ("El mínimo común múltiplo de", n, "y", m, "es",mcm(n,m))